package com.buyandsellstore.app.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

@Document(collection = "wishlistItems")
public class WishlistItem {

    @Id
    private String id;          // Unique identifier for the wishlist item (generated by MongoDB)
    private String userId;      // Which user this wishlist item belongs to
    private String itemId;      // ID of the item (similar to CartItem)
    private String type;        // e.g., "book", "homeItem", etc.
    private String name;        // Name of the item
    private double price;       // Price of the item
    private String imageUrl;    // URL for the item's image
    private Date createdAt;     // Date when this item was added to the wishlist

    // Constructors
    public WishlistItem() {
    }

    public WishlistItem(String userId, String itemId, String type, String name, double price, String imageUrl, Date createdAt) {
        this.userId = userId;
        this.itemId = itemId;
        this.type = type;
        this.name = name;
        this.price = price;
        this.imageUrl = imageUrl;
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getItemId() {
        return itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    // toString for debugging/logging
    @Override
    public String toString() {
        return "WishlistItem{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", itemId='" + itemId + '\'' +
                ", type='" + type + '\'' +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", imageUrl='" + imageUrl + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
